services:
  - type: web
    name: ai-skillfit-backend
    runtime: python
    rootDir: backend
    buildCommand: apt-get install -y libzbar0 libgl1 && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
